apiVersion: v1
kind: Service
metadata:
  name: silverwin
  namespace: silverwin
spec:
  type: LoadBalancer
  selector:
    app: silverwin
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
