# ------------------------
# Namespace
# ------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: silverwin

---
# ------------------------
# 1. Postgres Secret
# ------------------------
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: silverwin
type: Opaque
data:
  POSTGRES_USER: c3lsdmVyd2lu      # base64 of 'silverwin'
  POSTGRES_PASSWORD: c2VjdXJl      # base64 of your password

---
# ------------------------
# 2. Rails Secret
# ------------------------
apiVersion: v1
kind: Secret
metadata:
  name: rails-secret
  namespace: silverwin
type: Opaque
data:
  RAILS_SECRET_KEY_BASE: MEo3ejhKM2c5TjJqTDRkTQ==

---
# ------------------------
# 3. Postgres Deployment + Service
# ------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: silverwin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: silverwin
spec:
  selector:
    app: postgres
  ports:
    - port: 5432

---
# ------------------------
# 4. Redis Deployment + Service
# ------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: silverwin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: silverwin
spec:
  selector:
    app: redis
  ports:
    - port: 6379

---
# ------------------------
# 5. Rails App Deployment + Service
# ------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silverwin
  namespace: silverwin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silverwin
  template:
    metadata:
      labels:
        app: silverwin
    spec:
      containers:
        - name: silverwin
          image: matejci/silverwin:latest
          env:
            - name: RAILS_ENV
              value: production
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: RAILS_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-secret
                  key: RAILS_SECRET_KEY_BASE
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-master-key
                  key: RAILS_MASTER_KEY
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: silverwin
  namespace: silverwin
spec:
  type: LoadBalancer
  selector:
    app: silverwin
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
---
# ------------------------
# 6. Sidekiq Deployment
# ------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  namespace: silverwin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: matejci/silverwin:latest
          env:
            - name: RAILS_ENV
              value: production
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: RAILS_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-secret
                  key: RAILS_SECRET_KEY_BASE
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-master-key
                  key: RAILS_MASTER_KEY
          command: ["bundle", "exec", "sidekiq"]
